[package]
name = "tui-widget-list"
version = "0.12.0"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "Widget List for TUI/Ratatui"
repository = "https://github.com/preiter93/tui-widget-list"
keywords = ["tui", "ratatui", "widget", "list", "widgetlist"]
readme = "README.md"
license = "MIT"

[dependencies]
ratatui = "0.28"

[dev-dependencies]
crossterm = "0.28"

[[example]]
name = "simple"

[[example]]
name = "var_sizes"

[[example]]
name = "demo"

[[example]]
name = "demo_legacy"

[[example]]
name = "simple_legacy"

[features]
default = ["unstable-widget-ref"]
unstable-widget-ref = ["ratatui/unstable-widget-ref"]
