[package]
name = "tui-widget-list"
version = "0.2.3"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "Widget List for TUI/Ratatui"
repository = "https://github.com/preiter93/tui-widget-list"
keywords = ["tui", "ratatui", "widget", "list", "widgetlist"]
readme = "README.md"
license = "MIT"

[dependencies]
crossterm = "0.27"
ratatui = "0.23"

[[example]]
name = "paragraph_list"

[[example]]
name = "simple_list"
